name: Daily Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      buildNumber:
        description: 'Build Number'
        required: true
        default: '13686.1'
      buildYear:
        description: 'Build Year'
        required: true
        default: '2023'


env:
  WORKSPACE: ${{ github.workspace }}
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
  BUILD_NUMBER: ${{ github.event.inputs.buildNumber }}
  YEAR: ${{ github.event.inputs.buildYear }}

jobs:
  # source-code:
  #   name: Check out and process source code
  #   if: "!contains(github.ref, 'refs/tags/') || github.repository == 'zero-meta/solar2d-github-action-test'"
  #   runs-on: macos-11
  #   steps:
  #     - run: CDR="$(basename "$(pwd)")" ; cd .. ; rm -rf "$CDR" ; mkdir -p "$CDR" ; cd "$CDR"
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: recursive
  #     - run: ./tools/GHAction/daily_env.sh
  #     - name: Set daily build
  #       run: ./tools/GHAction/process_sources.sh
  #     - name: Upload Source bundle
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: SourceCode
  #         path: ./output

  # Windows-Simulator:
  #   needs:
  #     - source-code
  #   runs-on: windows-2019
  #   steps:
  #     - name: Get processed code
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: SourceCode
  #     - name: Unpack source code
  #       run: |
  #         7z x SourceCode/corona.tgz
  #         7z x corona.tar
  #     - run: ./tools/GHAction/daily_env.sh
  #       shell: bash
  #     - run: mkdir -f docs
  #     - name: Build Corona Simulator
  #       shell: cmd
  #       run: |
  #         cd platform\windows
  #         call UpdateFileVersions.bat %BUILD_NUMBER%
  #         call Build.Tools\VSVars.bat
  #         call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
  #         devenv "Corona.SDK.sln" /rebuild "Release|x86"
  #       env:
  #         WIN_CERT_PASSWORD: ${{ secrets.WinCertPassword }}

  Windows-Simulator:
    runs-on: windows-2019
    steps:
      - name: Build Corona Simulator
        shell: cmd
        run: |
          set /a majorVersion = %DATE:~-2%
          set /a minorVersion = %BUILD_NUMBER / 10000
          set /a buildNumber = %BUILD_NUMBER %% 10000
          echo %majorVersion% %minorVersion% %buildNumber%
